# Array mit Kategorien

CATEGORIES = ["human", "building", "landscape"]

#Methoden für das Vorverarbeiten der Bilder
PREPROCESS_METHODS = ["grayscaling", "edges", "frequencies"]

# Anzahl der Varianten je Prompt
SYNTHETIC_VARIANTEN_BEKANNT = 14
SYNTHETIC_VARIANTEN_UNBEKANNT = 6

MANIPULATED_VARIANTEN_BEKANNT = 14
MANIPULATED_VARIANTEN_UNBEKANNT = 6
MANIPULATED_HUMAN_VARIANTEN_BEKANNT = 7

# CNN Modelle
MODELS = [
    "xception71",
	"mobilenetv2_100",
    "tf_efficientnet_b3",
	"densenet121",
	"resnet50d",
	"convnext_small"
]

ALL_MODELS = [
    *MODELS,
    "weighted_ensemble",
    "unweighted_ensemble",
    "weighted_meta_classifier_ensemble",
    "unweighted_meta_classifier_ensemble",
]

# Trainingsvarianten
TRAININGS_VARIANTEN = [
    *CATEGORIES,
    *PREPROCESS_METHODS,
    "single_models"
]

TEST_VARIANTEN = [
    "known_test_dir",
    "unknown_test_dir",
    "known_test_jpeg_dir",
    "unknown_test_jpeg_dir",
    "known_test_noisy_dir",
    "unknown_test_noisy_dir",
    "known_test_scaled_dir",
    "unknown_test_scaled_dir",
    "known_test_occlusion",
    "unknown_test_occlusion",
    "known_test_insertion",
    "unknown_test_insertion",
    "known_test_format_png",
    "unknown_test_format_png",
    "known_test_format_webp",
    "unknown_test_format_webp",
    "known_test_histogram",
    "unknown_test_histogram"
]

# enthält Pfade und andere Parameter usw.
CONFIG = {
    "synthetic_images_log_path": "logs/image_synthesis/image_synthesis_log.csv",
    "manipulated_images_log_path": "logs/image_manipulation/image_manipulation_log.csv",

    "train_log_path": "logs/train",
    "train_human_result_log": "logs/train/human/train_results.csv",
    "train_building_result_log": "logs/train/building/train_results.csv",
    "train_landscape_result_log": "logs/train/landscape/train_results.csv",
    "train_grayscaling_result_log": "logs/train/grayscaling/train_results.csv",
    "train_edges_result_log": "logs/train/edges/train_results.csv",
    "train_frequencies_result_log": "logs/train/frequencies/train_results.csv",
    "train_single_models_result_log": "logs/train/single_models/train_results.csv",

    "train_classifier": "data/classifier/train",
    "val_classifier": "data/classifier/val",

    "checkpoint_classifier_dir": "checkpoints/classifier/classifier.pth",
    "checkpoint_dir": "checkpoints",

    "quality_stats_path": "logs/quality/quality_stats.json",

    "images_path": "images",

    "splited_images_path": "splited_images",

    "train_dir":"data/train",
    "val_dir":"data/val",

    "building_train_dir": "data/train/building",
    "building_val_dir": "data/val/building",
    "landscape_train_dir": "data/train/landscape",
    "landscape_val_dir": "data/val/landscape",
    "human_train_dir": "data/train/human",
    "human_val_dir": "data/val/human",
    "grayscale_train_dir": "data/train/grayscaling",
    "grayscale_val_dir": "data/val/grayscaling",
    "edges_train_dir": "data/train/edges",
    "edges_val_dir": "data/val/edges",
    "frequency_train_dir": "data/train/frequencies",
    "frequency_val_dir": "data/val/frequencies",

    "known_test_dir": "data/test/known_test",
    "unknown_test_dir": "data/test/unknown_test",
    "known_test_jpeg_dir": "data/test/known_test_jpeg",
    "unknown_test_jpeg_dir": "data/test/unknown_test_jpeg",
    "known_test_noisy_dir": "data/test/known_test_noisy",
    "unknown_test_noisy_dir": "data/test/unknown_test_noisy",
    "known_test_scaled_dir": "data/test/known_test_scaled",
    "unknown_test_scaled_dir": "data/test/unknown_test_scaled",

    "known_test_occlusion": "data/test/known_test_occlusion",
    "unknown_test_occlusion": "data/test/unknown_test_occlusion",
    "known_test_insertion": "data/test/known_test_insertion",
    "unknown_test_insertion": "data/test/unknown_test_insertion",
    "known_test_format_png": "data/test/known_test_format_png",
    "unknown_test_format_png": "data/test/unknown_test_format_png",
    "known_test_format_webp": "data/test/known_test_format_webp",
    "unknown_test_format_webp": "data/test/unknown_test_format_webp",
    "known_test_histogram": "data/test/known_test_histogram",
    "unknown_test_histogram": "data/test/unknown_test_histogram",
    "image_size": 224,
    "epochs": 30,
    "early_stopping_patience": 4,
    "batch_size":"",
    "learning_rate":""

}

# Prompts für synthetische Bilder
PROMPTS = {
    "human": [ # → 25 Prompts á 14 Varianten bzw. á 6 Varianten für unbekannten Datensatz
        "photo of a young boy with curly hair, smiling outdoors in the park",
        "photo of a young woman with dyed blue hair, street style fashion",
        "portrait photo of a young Asian woman with long black hair, natural daylight, 50mm lens",
        "portrait of an elderly Black man with gray beard, warm indoor lighting",
        "studio portrait of a middle-aged Caucasian woman with freckles, soft background",
        "professional headshot of a South Asian man with glasses, neutral background",
        "photo of a teenage girl in casual clothing, standing on a city street",
        "close-up portrait of a young Arab woman wearing a headscarf, soft light",
        "photo of an elderly East Asian woman with wrinkles, natural daylight",
        "portrait of a middle-aged Hispanic man, short hair, warm tone lighting",
        "group photo of three friends, mixed ethnicities, laughing in a café",
        "photo of a toddler with blond hair, sitting on the grass",
        "portrait of a young Black woman with braids, golden hour lighting",
        "photo of a middle-aged man with a beard, wearing a suit outdoors",
        "portrait of a teenage boy with acne, school hallway background",
        "photo of a pregnant woman smiling, home interior",
        "portrait of a man with long hair and tattoos, dramatic lighting",
        "photo of an elderly couple holding hands in a park",
        "portrait of a young Indigenous woman in traditional clothing",
        "photo of a middle-aged man with shaved head, gym background",
        "portrait of a young woman with glasses, in a library",
        "photo of a man in his 30s with a beard, winter jacket, snowy background",
        "close-up of a young child with face paint, festival background",
        "portrait of a middle-aged woman with short hair, workplace setting",
        "photo of a diverse group of five people posing outdoors, wide shot"
    ],
    "building": [ # → 25 Prompts á 14 Varianten bzw. á 6 Varianten für unbekannten Datensatz
        "modern glass skyscraper in city center, photographed at dusk",
        "old European cathedral with gothic details, daylight",
        "traditional Japanese wooden house, garden with lanterns",
        "minimalist concrete building, clean lines, overcast sky",
        "colorful houses along a canal, daytime",
        "desert adobe houses, warm sunset light",
        "classic New York brownstone street, autumn leaves",
        "futuristic office tower with curved glass, blue sky",
        "ancient stone castle on a hill, cloudy sky",
        "suburban residential street with family houses",
        "Greek island whitewashed buildings with blue roofs",
        "old industrial warehouse with brick walls",
        "wooden mountain cabin with chimney smoke",
        "modern museum building with geometric shapes",
        "abandoned farmhouse in rural field",
        "colorful colonial houses in Latin America",
        "mosque with detailed minarets, photographed at sunset",
        "modern luxury villa with swimming pool, daylight",
        "snow-covered alpine chalet with warm lights inside",
        "old European train station with glass roof",
        "skyscraper construction site with cranes",
        "traditional Chinese pagoda surrounded by trees",
        "apartment block with balconies, urban daylight",
        "ancient Roman amphitheater ruins",
        "small countryside church with stone walls"
    ],
    "landscape": [ # → 25 Prompts á 14 Varianten bzw. á 6 Varianten für unbekannten Datensatz
        "alpine mountain landscape at sunrise, snow peaks glowing",
        "dense rainforest with mist, sunlight filtering through trees",
        "desert dunes under clear blue sky, detailed sand textures",
        "northern lights over snowy forest, night sky full of stars",
        "coastal cliffs with crashing waves, overcast weather",
        "savannah landscape with acacia trees, golden hour",
        "autumn forest with colorful leaves, path covered in foliage",
        "volcanic landscape with lava fields, dramatic sky",
        "panoramic view of a glacier, icy textures",
        "rolling green hills in spring, wildflowers in bloom",
        "river winding through canyon, aerial perspective",
        "tropical beach with palm trees, turquoise water",
        "foggy moorland with rocky outcrops",
        "frozen lake with snow-covered pine trees",
        "desert oasis with palm trees and water pool",
        "grassland with grazing animals, cloudy sky",
        "mountain valley with river, summer daylight",
        "dramatic thunderstorm over open fields",
        "sunset over rice terraces, Southeast Asia",
        "snowy mountain village, smoke from chimneys",
        "desert plateau with cacti, midday sun",
        "vast tundra under cloudy sky, lonely feeling",
        "panoramic coastline with fishing boats, sunrise",
        "lush jungle waterfall, spray in the air",
        "rolling vineyards in summer, Mediterranean style"
    ]
}

EDIT_LIBRARY = {
    "landscape": {
        "img2img": [ # 25 Prompts
            "sunny summer field",
            "cloudy mountain view",
            "foggy forest",
            "snowy mountain slope",
            "desert under bright sun",
            "desert at dusk",
            "rocky coast in daylight",
            "rocky coast at sunset",
            "river in bright daylight",
            "river in foggy morning",
            "waterfall in daylight",
            "waterfall in cloudy weather",
            "meadow with flowers, sunny",
            "meadow with muted tones",
            "dense forest with shadows",
            "dense forest in morning sun",
            "hills under blue sky",
            "hills under stormy clouds",
            "field at golden hour",
            "field in overcast light",
            "winter scene with snow",
            "spring scene with green leaves",
            "autumn scene with colorful trees",
            "rainy forest path",
            "sunny forest path"
        ],
        "inpaint": [ # 25 Prompts
            "add small wooden cabin",
            "add tent in field",
            "add red car on dirt path",
            "add bicycle on path",
            "add flock of birds",
            "add single bird in sky",
            "add airplane in sky",
            "add small boat on water",
            "add person silhouette in distance",
            "add hikers on trail",
            "add campfire with smoke",
            "add picnic table",
            "add bench near path",
            "add road sign",
            "add electricity pole",
            "add wind turbine",
            "add small barn",
            "add tractor on field",
            "add hay bales",
            "add cow on meadow",
            "add sheep on meadow",
            "add dog near path",
            "add deer in forest",
            "add fox in forest",
            "add tree stump"
        ],
        "instruction": [ # 25 Prompts
            "make it snowy winter scene",
            "make it autumn with colorful leaves",
            "make it spring with blossoms",
            "make it summer with bright sun",
            "change to cloudy weather",
            "change to foggy weather",
            "add rain",
            "remove rain",
            "make it nighttime with stars",
            "make it sunset",
            "make it sunrise",
            "add cabin in distance",
            "remove cabin",
            "add flock of birds",
            "remove birds",
            "add car on road",
            "remove car",
            "add hikers",
            "remove hikers",
            "add campfire",
            "remove campfire",
            "add river",
            "remove river",
            "make it more green",
            "make it less green"
        ],
    },
    "building": {
        "img2img": [ # 25 Prompts
            "modern glass facade, daylight",
            "building under cloudy sky",
            "building at night with lit windows",
            "building with neon signs",
            "suburban house with warm evening light",
            "office tower at dusk",
            "building with rain reflections",
            "facade under bright noon sun",
            "building in foggy atmosphere",
            "historic building under daylight",
            "brick building in golden hour",
            "building with muted film colors",
            "apartment block at night",
            "shopping mall entrance with lights",
            "house in snowy environment",
            "building with overexposed light",
            "small house with garden in daylight",
            "school building, cloudy sky",
            "train station facade at dusk",
            "building in urban street view",
            "skyscraper under blue sky",
            "building with cars in front",
            "building under stormy clouds",
            "building in winter daylight",
            "industrial building, daytime"
        ],
        "inpaint": [ # 25 Prompts
            "add ivy on facade",
            "add graffiti on wall",
            "add small balcony",
            "add flower pots on windowsill",
            "add air conditioning unit",
            "add satellite dish",
            "add street lamp in front",
            "add tree shadow on wall",
            "add small shop sign",
            "add cafe table outside",
            "add parked bicycle",
            "add parked scooter",
            "add trash bin",
            "add fire hydrant",
            "add traffic sign",
            "add car parked in front",
            "add small bench near wall",
            "add flag on facade",
            "add open window",
            "add closed shutters",
            "add curtain visible inside",
            "add door mat",
            "add mailbox on wall",
            "add railing on stairs",
            "add security camera"
        ],
        "instruction": [ # 25 Prompts
            "make it nighttime with lit windows",
            "make it sunset atmosphere",
            "make it early morning light",
            "add ivy to facade",
            "remove ivy from facade",
            "add graffiti",
            "remove graffiti",
            "add balcony",
            "remove balcony",
            "make facade clean",
            "make facade dirty",
            "change facade color to white",
            "change facade color to beige",
            "change facade color to gray",
            "change roof color to red",
            "change roof color to gray",
            "add lit street lamp",
            "remove street lamp",
            "add open window",
            "close windows",
            "add shop sign",
            "remove shop sign",
            "add shutters",
            "remove shutters",
            "make building look older"
        ],
    },
    "human": {
        "img2img": [ # 25 Prompts
            "neutral portrait under soft daylight",
            "portrait with strong contrast lighting",
            "indoor portrait with warm artificial light",
            "portrait in a car, daylight through window",
            "street portrait, overcast sky",
            "portrait at dusk, natural backlight",
            "portrait with subtle film grain effect",
            "indoor portrait with white wall background",
            "portrait with warm golden hour tones",
            "portrait under cold neon light",
            "portrait outdoors with blurred city lights",
            "office portrait, fluorescent lighting",
            "portrait in kitchen environment",
            "portrait with slight vignette effect",
            "portrait near a window with natural light",
            "portrait outdoors with greenery background",
            "portrait in park, afternoon sun",
            "portrait in subway station, artificial lights",
            "portrait with light shadow across face",
            "portrait with subtle skin smoothing",
            "black and white portrait conversion",
            "portrait with balanced studio lighting",
            "portrait with shallow depth of field",
            "portrait under cloudy daylight",
            "portrait illuminated by laptop screen"
        ],
        "inpaint": [ # 25 Prompts
            "add sunglasses",
            "add eyeglasses",
            "add baseball cap",
            "add winter beanie",
            "add hoop earrings",
            "add stud earrings",
            "add freckles on cheeks",
            "add mole on face",
            "add subtle beard stubble",
            "add mustache",
            "add small scar on cheek",
            "add scar on forehead",
            "add subtle makeup on lips",
            "add blush on cheeks",
            "add eyeliner",
            "add nose piercing",
            "add eyebrow piercing",
            "add lip piercing",
            "add short necklace",
            "add hoodie hood on head",
            "add headset on ears",
            "add bluetooth earpiece",
            "add airpods",
            "add wireless headphones",
            "add headscarf"
        ],
        "instruction": [ # 25 Prompts
            "change hair color to blonde",
            "change hair color to brown",
            "change hair color to black",
            "change hair color to red",
            "add subtle beard",
            "add thicker beard",
            "remove beard",
            "add eyeglasses",
            "remove eyeglasses",
            "add sunglasses",
            "add freckles",
            "remove freckles",
            "smooth skin slightly",
            "add wrinkles around eyes",
            "reduce wrinkles",
            "make person smile",
            "make person neutral expression",
            "make person serious expression",
            "close mouth slightly",
            "open mouth slightly",
            "add subtle makeup",
            "add heavy makeup",
            "remove makeup",
            "add scar on cheek",
            "add a hat"
        ],
    },
}
